import './globals.css'
import type { Metadata } from 'next'
import Navbar from './Navbar'
import { Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <Navbar />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  )
}
